/* Generated by re2c 0.13.5 on Tue Jun 21 17:05:07 2011 */
/*
  +----------------------------------------------------------------------+
  | PHP Version 5                                                        |
  +----------------------------------------------------------------------+
  | Copyright (c) 1997-2010 The PHP Group                                |
  +----------------------------------------------------------------------+
  | This source file is subject to version 3.01 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.php.net/license/3_01.txt                                  |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Author: Gasol Wu <gasol.wu@gmail.com>                                |
  +----------------------------------------------------------------------+
*/
#include "php.h"

#define YYCTYPE         unsigned char
#define YYCURSOR        cql
#define YYLIMIT         cql
#define YYMARKER		q
#define YYFILL(n)

char *tokendup(char *str)
{
	int len = 0;
	char *begin = str;
    char ch = NULL;
	while (ch = *str) {
        if (ch == ' ') {
            break;
        }
        ++len;
		++str;
	}
	if (len > 0) {
		char *ret = emalloc(len+1);
		strncpy(ret, begin, len);
        ret[len] = '\0';
		return ret;
	} else {
		return NULL;
	}
}

char *scan_columnfamily(char *cql)
{
	char *q;

{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 10) YYFILL(10);
	yych = *YYCURSOR;
	if (yych <= 'R') {
		if (yych != ' ') goto yy5;
	} else {
		if (yych <= 'S') goto yy4;
		if (yych == 's') goto yy4;
		goto yy5;
	}
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 'R') {
		if (yych == ' ') goto yy28;
	} else {
		if (yych <= 'S') goto yy27;
		if (yych == 's') goto yy27;
	}
yy3:
	{return (char*) 0;}
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'E') goto yy6;
	if (yych == 'e') goto yy6;
	goto yy3;
yy5:
	yych = *++YYCURSOR;
	goto yy3;
yy6:
	yych = *++YYCURSOR;
	if (yych == 'L') goto yy8;
	if (yych == 'l') goto yy8;
yy7:
	YYCURSOR = YYMARKER;
	if (yyaccept <= 0) {
		goto yy3;
	} else {
		goto yy26;
	}
yy8:
	yych = *++YYCURSOR;
	if (yych == 'E') goto yy9;
	if (yych != 'e') goto yy7;
yy9:
	yych = *++YYCURSOR;
	if (yych == 'C') goto yy10;
	if (yych != 'c') goto yy7;
yy10:
	yych = *++YYCURSOR;
	if (yych == 'T') goto yy11;
	if (yych != 't') goto yy7;
yy11:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy7;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy15;
	goto yy14;
yy13:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy14:
	if (yych == '\n') goto yy7;
	if (yych == ' ') goto yy19;
	goto yy13;
yy15:
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy14;
yy16:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= ' ') {
		if (yych == '\n') goto yy7;
		if (yych <= 0x1F) goto yy13;
		goto yy16;
	} else {
		if (yych <= 'F') {
			if (yych <= 'E') goto yy13;
		} else {
			if (yych != 'f') goto yy13;
		}
	}
yy18:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= ' ') {
		if (yych == '\n') goto yy7;
		if (yych <= 0x1F) goto yy13;
	} else {
		if (yych <= 'R') {
			if (yych <= 'Q') goto yy13;
			goto yy21;
		} else {
			if (yych == 'r') goto yy21;
			goto yy13;
		}
	}
yy19:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= ' ') {
		if (yych == '\n') goto yy7;
		if (yych <= 0x1F) goto yy13;
		goto yy19;
	} else {
		if (yych <= 'F') {
			if (yych <= 'E') goto yy13;
			goto yy18;
		} else {
			if (yych == 'f') goto yy18;
			goto yy13;
		}
	}
yy21:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= ' ') {
		if (yych == '\n') goto yy7;
		if (yych <= 0x1F) goto yy13;
		goto yy19;
	} else {
		if (yych <= 'O') {
			if (yych <= 'N') goto yy13;
		} else {
			if (yych != 'o') goto yy13;
		}
	}
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= ' ') {
		if (yych == '\n') goto yy7;
		if (yych <= 0x1F) goto yy13;
		goto yy19;
	} else {
		if (yych <= 'M') {
			if (yych <= 'L') goto yy13;
		} else {
			if (yych != 'm') goto yy13;
		}
	}
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych == '\n') goto yy7;
	if (yych != ' ') goto yy13;
yy24:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	if (yych <= ' ') {
		if (yych == '\n') goto yy26;
		if (yych <= 0x1F) goto yy13;
		goto yy24;
	} else {
		if (yych <= 'F') {
			if (yych <= 'E') goto yy13;
			goto yy18;
		} else {
			if (yych == 'f') goto yy18;
			goto yy13;
		}
	}
yy26:
	{return tokendup(YYCURSOR);}
yy27:
	yych = *++YYCURSOR;
	if (yych == 'E') goto yy6;
	if (yych == 'e') goto yy6;
	goto yy7;
yy28:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
	yych = *YYCURSOR;
	if (yych <= 'R') {
		if (yych == ' ') goto yy28;
		goto yy7;
	} else {
		if (yych <= 'S') goto yy27;
		if (yych == 's') goto yy27;
		goto yy7;
	}
}

}
