#!/bin/sh

PHP=$(which php)
PHP_TEST_EXECUTABLE=$PHP
PHPCONFIG=$(which php-config)
MODULE_DIR="./modules/"
EXTENSION_DIR="`$PHPCONFIG --extension-dir`"

TEST_PHP_EXECUTABLE=$PHP $PHP run-tests.php -n -d extension_dir=$MODULE_DIR -d extension=$EXTENSION_DIR/pdo.so -d extension=pdo_cassandra.so $1 $2
