Document: php5-cassandra
Title: Debian php5-cassandra Manual
Author: <insert document author here>
Abstract: This manual describes what php5-cassandra is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/php5-cassandra/php5-cassandra.sgml.gz

Format: postscript
Files: /usr/share/doc/php5-cassandra/php5-cassandra.ps.gz

Format: text
Files: /usr/share/doc/php5-cassandra/php5-cassandra.text.gz

Format: HTML
Index: /usr/share/doc/php5-cassandra/html/index.html
Files: /usr/share/doc/php5-cassandra/html/*.html
